CREATE TABLE usuarios (
    biblio_karmas integer,
    id            integer generated by default as identity,
    register_date date,
    description   varchar(500),
    city          varchar(255),
    email         varchar(255) not null unique,
    full_name     varchar(255) not null,
    img_url       varchar(255),
    password      varchar(255),
    phone         varchar(255),
    primary key (id)
);

-- Los libros viven en MongoDB: no se crea tabla libros en PostgreSQL.
-- reservaciones guarda el book_id como VARCHAR (ObjectId de MongoDB)
-- y desnormaliza los datos del libro para evitar joins entre BD.
CREATE TABLE reservaciones (
    id              integer      generated by default as identity,
    owner_id        integer,
    reader_id       integer,
    book_id         varchar(36)  not null,
    book_owner_id   integer      not null default 0,
    book_title      varchar(500) not null default '',
    book_author     varchar(255) not null default '',
    book_genre      varchar(255) not null default '',
    book_state      varchar(50)  not null default 'BUENO'
                        check (book_state in ('EXCELENTE','MUY_BUENO','BUENO','MALO','REGULAR')),
    book_img_url    text         not null default '',
    book_owner_name varchar(255) not null default '',
    from_date       date,
    until_date      date,
    rating          float(53),
    comment         varchar(500),
    primary key (id)
);

CREATE TABLE roles (
    id   BIGSERIAL    PRIMARY KEY,
    name VARCHAR(50)  NOT NULL UNIQUE
);

CREATE TABLE user_types (
    user_id INTEGER NOT NULL REFERENCES usuarios(id),
    role_id BIGINT  NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);

ALTER TABLE reservaciones
    ADD CONSTRAINT fk_reservaciones_owner
    FOREIGN KEY (owner_id)
    REFERENCES usuarios;

ALTER TABLE reservaciones
    ADD CONSTRAINT fk_reservaciones_reader
    FOREIGN KEY (reader_id)
    REFERENCES usuarios;
